// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfpKcy8-Q0njQtWCoEB3aOxSx_sZ0xato',
    appId: '1:205919215363:web:006646b9ac2db18db8d336',
    messagingSenderId: '205919215363',
    projectId: 'redwood-666f7',
    authDomain: 'redwood-666f7.firebaseapp.com',
    storageBucket: 'redwood-666f7.appspot.com',
    measurementId: 'G-JCRWJ657NY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFA26NrPpPAWTuCbt_JXu-G8Qi7IGqw3E',
    appId: '1:205919215363:android:ce3365ad76c89121b8d336',
    messagingSenderId: '205919215363',
    projectId: 'redwood-666f7',
    storageBucket: 'redwood-666f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPI57LNBrqGcvzvXpV_Yh0SBs-1xnD68Y',
    appId: '1:205919215363:ios:5be1164f6399959ab8d336',
    messagingSenderId: '205919215363',
    projectId: 'redwood-666f7',
    storageBucket: 'redwood-666f7.appspot.com',
    androidClientId: '205919215363-04itkvvh1bmmp2vu56q0s6qo4lvf6f2m.apps.googleusercontent.com',
    iosClientId: '205919215363-4meotjld195kl48q1jo2at9jgv6l6r6p.apps.googleusercontent.com',
    iosBundleId: 'com.example.web',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPI57LNBrqGcvzvXpV_Yh0SBs-1xnD68Y',
    appId: '1:205919215363:ios:5be1164f6399959ab8d336',
    messagingSenderId: '205919215363',
    projectId: 'redwood-666f7',
    storageBucket: 'redwood-666f7.appspot.com',
    androidClientId: '205919215363-04itkvvh1bmmp2vu56q0s6qo4lvf6f2m.apps.googleusercontent.com',
    iosClientId: '205919215363-4meotjld195kl48q1jo2at9jgv6l6r6p.apps.googleusercontent.com',
    iosBundleId: 'com.example.web',
  );
}
