///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class Images {

  int? id;
  int? projectId;
  String? image;
  String? createdAt;
  String? updatedAt;

  Images({
    this.id,
    this.projectId,
    this.image,
    this.createdAt,
    this.updatedAt,
  });
  Images.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    projectId = json['project_id']?.toInt();
    image = json['image']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['project_id'] = projectId;
    data['image'] = image;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    return data;
  }
}

class Pivot {

  int? projectId;
  int? userId;

  Pivot({
    this.projectId,
    this.userId,
  });
  Pivot.fromJson(Map<String, dynamic> json) {
    projectId = json['project_id']?.toInt();
    userId = json['user_id']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['project_id'] = projectId;
    data['user_id'] = userId;
    return data;
  }
}

class Users {

  int? id;
  String? name;
  String? email;
  String? employeeId;
  String? userRoleId;
  String? phone;
  String? officeNumber;
  String? address;
  String? photo;
  String? brand;
  String? position;
  String? team;
  String? region;
  int? countryId;
  String? otp;
  int? isVerified;
  String? status;
  String? updatedAt;
  String? createdAt;
  Pivot? pivot;

  Users({
    this.id,
    this.name,
    this.email,
    this.employeeId,
    this.userRoleId,
    this.phone,
    this.officeNumber,
    this.address,
    this.photo,
    this.brand,
    this.position,
    this.team,
    this.region,
    this.countryId,
    this.otp,
    this.isVerified,
    this.status,
    this.updatedAt,
    this.createdAt,
    this.pivot,
  });
  Users.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    email = json['email']?.toString();
    employeeId = json['employee_id']?.toString();
    userRoleId = json['user_role_id']?.toString();
    phone = json['phone']?.toString();
    officeNumber = json['office_number']?.toString();
    address = json['address']?.toString();
    photo = json['photo']?.toString();
    brand = json['brand']?.toString();
    position = json['position']?.toString();
    team = json['team']?.toString();
    region = json['region']?.toString();
    countryId = json['country_id']?.toInt();
    otp = json['otp']?.toString();
    isVerified = json['is_verified']?.toInt();
    status = json['status']?.toString();
    updatedAt = json['updated_at']?.toString();
    createdAt = json['created_at']?.toString();
    pivot = (json['pivot'] != null) ? Pivot.fromJson(json['pivot']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['email'] = email;
    data['employee_id'] = employeeId;
    data['user_role_id'] = userRoleId;
    data['phone'] = phone;
    data['office_number'] = officeNumber;
    data['address'] = address;
    data['photo'] = photo;
    data['brand'] = brand;
    data['position'] = position;
    data['team'] = team;
    data['region'] = region;
    data['country_id'] = countryId;
    data['otp'] = otp;
    data['is_verified'] = isVerified;
    data['status'] = status;
    data['updated_at'] = updatedAt;
    data['created_at'] = createdAt;
    if (pivot != null) {
      data['pivot'] = pivot!.toJson();
    }
    return data;
  }
}

class ProjectCategory {

  String? name;
  String? color;

  ProjectCategory({
    this.name,
    this.color,
  });
  ProjectCategory.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    color = json['color']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['color'] = color;
    return data;
  }
}

class ProjectDetails {

  int? id;
  String? projectCode;
  String? projectName;
  String? title;
  String? image;
  String? logo;
  String? address;
  String? description;
  String? projectStartDate;
  String? projectEndDate;
  String? projectStatus;
  String? status;
  String? createdAt;
  String? updatedAt;
  List<ProjectCategory?>? projectCategory;
  List<Users?>? users;
  List<Images?>? projectImages;

  ProjectDetails({
    this.id,
    this.projectCode,
    this.projectName,
    this.title,
    this.image,
    this.logo,
    this.address,
    this.description,
    this.projectStartDate,
    this.projectEndDate,
    this.projectStatus,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.projectCategory,
    this.users,
    this.projectImages,
  });
  ProjectDetails.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    projectCode = json['project_code']?.toString();
    projectName = json['project_name']?.toString();
    title = json['title']?.toString();
    image = json['image']?.toString();
    logo = json['logo']?.toString();
    address = json['address']?.toString();
    description = json['description']?.toString();
    projectStartDate = json['project_start_date']?.toString();
    projectEndDate = json['project_end_date']?.toString();
    projectStatus = json['project_status']?.toString();
    status = json['status']?.toString();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
    if (json['project_category'] != null) {
      final v = json['project_category'];
      final arr0 = <ProjectCategory>[];
      v.forEach((v) {
        arr0.add(ProjectCategory.fromJson(v));
      });
      projectCategory = arr0;
    }
    if (json['users'] != null) {
      final v = json['users'];
      final arr0 = <Users>[];
      v.forEach((v) {
        arr0.add(Users.fromJson(v));
      });
      users = arr0;
    }
    if (json['project_images'] != null) {
      final v = json['project_images'];
      final arr0 = <Images>[];
      v.forEach((v) {
        arr0.add(Images.fromJson(v));
      });
      projectImages = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['project_code'] = projectCode;
    data['project_name'] = projectName;
    data['title'] = title;
    data['image'] = image;
    data['logo'] = logo;
    data['address'] = address;
    data['description'] = description;
    data['project_start_date'] = projectStartDate;
    data['project_end_date'] = projectEndDate;
    data['project_status'] = projectStatus;
    data['status'] = status;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    if (projectCategory != null) {
      final v = projectCategory;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['project_category'] = arr0;
    }
    if (users != null) {
      final v = users;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['users'] = arr0;
    }
    if (projectImages != null) {
      final v = projectImages;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['project_images'] = arr0;
    }
    return data;
  }
}

class Data {
  List<ProjectDetails?>? projectDetails;
  List<String?>? images;

  Data({
    this.projectDetails,
    this.images,
  });
  Data.fromJson(Map<String, dynamic> json) {
    if (json['project_details'] != null) {
      final v = json['project_details'];
      final arr0 = <ProjectDetails>[];
      v.forEach((v) {
        arr0.add(ProjectDetails.fromJson(v));
      });
      projectDetails = arr0;
    }
    if (json['images'] != null) {
      final v = json['images'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      images = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (projectDetails != null) {
      final v = projectDetails;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v!.toJson());
      }
      data['project_details'] = arr0;
    }
    if (images != null) {
      final v = images;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v);
      }
      data['images'] = arr0;
    }
    return data;
  }
}

class ProjectInfoModal {

  bool? success;
  String? message;
  Data? data;

  ProjectInfoModal({
    this.success,
    this.message,
    this.data,
  });
  ProjectInfoModal.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    message = json['message']?.toString();
    data = (json['data'] != null) ? Data.fromJson(json['data']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['message'] = message;
    if (data != null) {
      data['data'] = this.data!.toJson();
    }
    return data;
  }
}
